NEST-300: Upgrading to .NET 6.0 and making theme work with UI testing
Lombiq/TheBootstrapTheme pull request #6
Opened 2022-02-05 01:58 UTC by DemeSzabolcs

NEST-300

2022-02-07 21:04 UTC, Piedone approved these changes

2022-02-08 19:43 UTC, Piedone requested changes

2022-02-08 20:12 UTC, DemeSzabolcs commented on src/TheBootstrapTheme/Views/Layout.cshtml
> +            <ul class="navbar-nav ms-auto"></ul>
Igen, azért. Akkor visszaírom és fixelem.

2022-02-10 11:05 UTC, Piedone requested changes

2022-02-10 12:35 UTC, DemeSzabolcs commented on src/TheBootstrapTheme/Recipes/TheBootstrapTheme.recipe.json
> +              "Text": "[asset_url]Images/placeholder-image-750x450.png[/asset_url]"
De van: https://github.com/Lombiq/TheBootstrapTheme/blob/7f85675e003c84d1c8c29cdb45581d6407a12ec2/src/TheBootstrapTheme/Recipes/TheBootstrapTheme.Tests.recipe.json

2022-02-10 14:00 UTC, DemeSzabolcs commented on src/TheBootstrapTheme/Recipes/TheBootstrapTheme.recipe.json
> +              "Text": "[asset_url]Images/placeholder-image-750x450.png[/asset_url]"
1. Az About pagnek az a része Raw Html widget ahol ezek a képek vannak (ez okozza az errort, nem az amit jelöltél). Ezt jó ha kicserélem `liquid`-re? (Az már úgy is van használva ezen az oldalon) Ott lehet `[asset_url]`-ezni.
 
2. Team membernél meg ugye csak egy text field van (ez az amit jelöltél, ez nem okoz errort, de attól a képeket nem tölti be). Itt ki lehetne cserélni media fieldre, de ott nem tudom hogy mikor megadom recepibe a pathot, lehet-e `[asset_url]`-ezni, vagy milyen olyan field van ami alkalmas erre.

2022-02-10 14:25 UTC, Piedone commented on src/TheBootstrapTheme/Recipes/TheBootstrapTheme.recipe.json
> +              "Text": "[asset_url]Images/placeholder-image-750x450.png[/asset_url]"
1. Liquidben nem tudsz shortcode-ot használni, azt csak Html fieldben/Body Partban. Az lenne a jobb. De ha nem megy, Liquid is lehet, de ott az assetes tag kell.
2. Media Field tökéletes, és nem kell ott ezzel foglalkozni, a field megcsinálja magától.

2022-02-11 16:46 UTC, Piedone approved these changes

2022-02-13 22:06 UTC, merged